### ISSUE TITLE
Statistic interpretation in CNVeQTL analysis

### ISSUE THREAD

**Issue by jessicadlang** [mkelly9513/OV-Project-One#1]
The findings in your paper are extremely interesting. Kudos for this exciting work!

I am interested in the output of the CNVeQTL analysis, but was wondering if you could help confirm the interpretation of the output for me. It seems from the code that the statistic is the t-statistic from the MatrixEQTL tool. Would a positive value indicate that the SE is associated with amplification, and negative value that the SE is associated with deletion?

Thanks!

**Comment by mkelly9513** [comment]
Hey jessicadlang, 

Thanks for the kind words! This is an excellent question! Yes, I used the MatrixEQTL tool in its linear model mode, so the t-statistic is the test statistic.

The interpretation of these data can get complicated however due to the fact we are dealing with genomics data (where gene expression values are sometimes co-linear with one another) and the use of a quantitative dataset for SNPs (float values of normalized CNV values from TCGA) whereas most eQTL analysis use a qualitative variable for SNP (such as "T" or "A"). These issues both influence the data and make direct interpretation difficult. This analysis DOES allow you to identify what regions of the genome are potentially associated in some way with the expression of genes, but I do not think that we can look too far into the mechanics of HOW with this analysis alone. Additional data would likely be needed (or the structure of data would need to be adjusted) to make those kinds of direct conclusions. I will lay out an example of how things can be tricky below. 

You are correct in that both positive and negative t values are significant and they signify different things, the beta value (effect size) is probably the easiest to interpret but it doesn't necessarily mirror the genetic landscape. A negative beta (which is associated with a negative t) means that the "variant" (CNV value in my case) is associated with a decrease in gene expression. This is potentially (and I would think often) due to a deletion but it could also be due to an amplification because of the co-linearity of genes. 

Example:
Co-linearity: 
Gene A negatively regulates Gene B, so as A increases B will decrease. 

CNV:
There is an amplification event (we will call this SNPA) that affects Gene A, increasing its expression. Due to co-linearity this increase in expression of Gene A decreases the expression of Gene B. 

eQTL Results:
The amplification of this region increases Gene A expression (positive beta and t statistic)

This amplification of this same region decreases Gene B expression (negative beta and t statistic)  

So the same SNP location and pattern (an amplification) could have an inverse effect on the expression of a gene which, to my knowledge would flip the beta effect and t-statistic. The reverse could also be true, a deletion event could increase the expression of a gene by down-regulating something within it's gene network. 

Takeaway:
This analysis will allow you to determine there is potentially a link between a region (represented by SNPA) and genes (in this case GeneA and GeneB) but directly assessing the relationship would require using additional data. I would think that in general most of the positive beta effects are associated with amplification and most of the negative beta effects are due to deletions but it is impossible to definitively lay out rules due to the issues mentioned above. 

That is why we used this as supplemental information for the project (often in combination with additional types of data such as RNA-Seq from KO experiments or Hi-C) as it is more of a high level exploration method (to form tentative links between regions and genes regardless of whether its a positive or negative association) than a direct linkage analysis. I think transforming the input SNP data into a qualitative data set (so that it matches traditional eQTL data where instead of a "T" or "A" at a location the SNP is  "Amplified", "Deleted", or "Diploid") could help with the interpretation of the results, as could leveraging the float values (such as looking at the median CNV across a SNP to see if it is amplified or deleted on average) but we didn't explore those facets of the data. 

Thanks again for the interest and the thoughtful question and I hope that this response either helped to explain the situation or could inspire alterations to the ideology for future researchers.
